# Generated by Django 5.2.13 on 2026-04-20 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateTimeField(auto_now_add=True, verbose_name='Data i godzina zgłoszenia')),
                ('subject', models.CharField(max_length=200, verbose_name='Temat zgłoszenia')),
                ('description', models.TextField(verbose_name='Treść/opis problemu')),
                ('module', models.CharField(choices=[('offer', 'Oferta'), ('offer-mng', 'Zarządzanie ofertą'), ('register', 'Rejestracja')], max_length=50, verbose_name='Moduł aplikacji')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='issues_attachments/', verbose_name='Opcjonalne załączniki')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor zgłoszenia')),
            ],
        ),
    ]
