# Generated by Django 5.2.13 on 2026-04-20 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publikuj')),
                ('order', models.IntegerField(default=0, verbose_name='Kolejność')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='offer.category', verbose_name='Kategoria nadrzędna')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Kolejność')),
                ('number', models.CharField(max_length=50, verbose_name='Numer')),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł')),
                ('description', models.TextField(verbose_name='Opis')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena')),
                ('hours', models.IntegerField(verbose_name='Liczba godzin')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publikuj')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.category', verbose_name='Kategoria')),
            ],
        ),
    ]
