# Generated by Django 5.2.13 on 2026-04-20 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content_html', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodo_consent', models.BooleanField(default=False, verbose_name='Zgoda RODO')),
                ('status', models.CharField(default='Nowa', max_length=50, verbose_name='Status')),
                ('date_registered', models.DateTimeField(auto_now_add=True, verbose_name='Data i godzina rejestracji')),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.course', verbose_name='Id szkolenia')),
            ],
        ),
    ]
